# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVMTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'SnapKit', '~> 4.0.0'
  pod 'RxCocoa', '~> 4.0'
  pod 'Moya/RxSwift', '~> 10.0.1'
  pod 'ObjectMapper'
  pod 'RxDataSources', '~> 3.0'
  # Pods for MVVMTest

end
