# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

def rx_swift
    pod 'RxSwift'
end

def rx_cocoa
    pod 'RxCocoa'
end


target 'CleanArchitectureRx' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  rx_swift
  rx_cocoa
  pod 'QueryKit'
end

target 'Domain' do
  use_frameworks!
  rx_swift
end
